## user:password@tcp(127.0.0.1:3306)/userdb?charset=utf8&parseTime=True&loc=Local
#mysql:
#  user: root
#  password: password
#  host: 127.0.0.1
#  port: 3306
#  name: userdb
#  charset: utf8
#  parseTime: true
#  loc: Local
#
#server:
#  port: 8080
#log:
#  level: debug
#  output: app.log
#
#grpc:
#  host: 127.0.0.1
#  port: 50051

